Apply matchers on the LHS to give their equals method priority
hypothesis/h-matchers pull request #30
Opened 2020-10-23 12:57 UTC by jon-betts

When trying to compare certain items with their own equals method this
would previously have called the compared object's method, rather than
the matcher.

This allows us to match un-cooperative objects.

2020-10-23 13:03 UTC, jon-betts commented on tests/unit/h_matchers/matcher/combination_test.py
> +            ]
New version of black

2020-10-23 13:03 UTC, jon-betts commented on src/h_matchers/matcher/combination.py
> +            lambda other: other in options,
New version of black

2020-10-23 13:09 UTC, jon-betts commented on bin/next_version.py
> +            raise FileNotFoundError("setup.cfg") from None
New version of lint

2020-10-29 11:23 UTC, seanh commented
I'm trying to figure out what this does but I seem to be getting the same behaviour on master as on this branch. @jon-betts Can you add an example of what this changes?

Example of what I'm seeing:

```python
>>> class NeverMatches:
...     def __eq__(self, other):
...         return False
... 
>>> import h_matchers
>>> NeverMatches() == h_matchers.Any()
False
>>> h_matchers.Any() == NeverMatches()
True
```

On this branch:

```python
>>> class NeverMatches:
...     def __eq__(self, other):
...         return False
... 
>>> import h_matchers
>>> NeverMatches() == h_matchers.Any()
False
>>> h_matchers.Any() == NeverMatches()
True
>>> 
```

2020-10-29 11:24 UTC, seanh requested changes
Need an example of what this does, added to the PR comments

2020-10-29 11:31 UTC, seanh commented
Ok, this seems to be the difference:

Master:

```python
>>> [NeverMatches()] == Any.list.comprised_of(Any())
False
```

This branch:

```python
>>> [NeverMatches()] == Any.list.comprised_of(Any())
True
```

And it also seems to work the other way round -- `Any.list.comprised_of(Any()) == [NeverMatches()]` returns `True` on this branch, `False` on master.

Is that it?

2020-10-29 19:43 UTC, jon-betts commented
I've rebased away some of the black mess, which hopefully make this clearer.

The two fixes are for `AllOf` matchers, and `comprised_of` matchers as you spotted.

The two places that are fixed are here:

 * https://github.com/hypothesis/h-matchers/pull/30/files#diff-29f68692dcf6b3c7cfbf55c75272d5f83751a9a5f730701b69f387e004f980e2L41
 * https://github.com/hypothesis/h-matchers/pull/30/files#diff-29f68692dcf6b3c7cfbf55c75272d5f83751a9a5f730701b69f387e004f980e2L41

There are two tests which demonstrate the failing cases here:

 * https://github.com/hypothesis/h-matchers/pull/30/files#diff-d40ad8bb81e20dfb2e5b13ac83ee89518bc05c83552b70b716f51be2c070a3adR32
 * https://github.com/hypothesis/h-matchers/pull/30/files#diff-e651a8c8edbd4a1f9fb518a6eefa4f8c0d22426f7fb17f0a04a544efa180a360R53

2020-10-30 12:40 UTC, robertknight approved these changes
LGTM

2020-10-30 13:21 UTC, merged