Attempt to make support h-matchers multiple python versions
hypothesis/h-matchers pull request #34
Opened 2021-04-01 16:52 UTC by jon-betts

Add support for Python 3.7, 3.8 and 3.9.

The idea here is to:

 * Get something which passes locally and in CI
 * Demonstrates how we might do it
 * Attempts to make it as templated as possible
 * Provides a platform to ship off into `hdev` or something similar

2021-04-01 17:39 UTC, seanh commented on tox.ini
> +envlist = py36-tests,py37-tests,py38-tests,py39-tests
I think this should work:
```suggestion
envlist = {py36,py37,py38,py39}-tests
```

2021-04-02 13:33 UTC, jon-betts commented on tox.ini
> +envlist = py36-tests,py37-tests,py38-tests,py39-tests
Yeah it does. This is how we are generating the versions from the script, although this is happening in the Makefile now

2021-04-02 13:34 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +  metadata:
This metadata phase takes about 6 seconds

2021-04-02 13:35 UTC, jon-betts commented on bin/python_codes.py
> +#!/usr/bin/env python
This will presumably end up squirrelled away in `hdev` in coming tickets

2021-04-02 13:35 UTC, jon-betts commented on setup.cfg
> +    Programming Language :: Python :: 3.9
I can't see a super easy way to template this in, but it's not all that onerous  to keep these up to date. The script will generate them for convenience.

2021-04-02 13:37 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +
Some of this is robbed from @marcospri 's PR here: https://github.com/hypothesis/hdev/pull/4

The examples of how to set outputs etc. was cribbed from here: https://github.com/frezbo/dockerfiles/blob/6701b8cffc3b3628ad72b541d2c36ac87e1e9b8f/.github/workflows/ci.yml

2021-04-02 13:40 UTC, jon-betts commented on .python-version
> +3.6.13
This file now has a lot more meaning than before:

 * The first entry is taken as the version to run linting against
 * You can add `# future` to include a version in `make testall` but not CI
 * You can add `# floating` to have the version vagued up to `3.9.x` in CI
 * You can add both at once, so for example we could have `3.10.0  # future floating`
 * This doesn't currently make much sense as the floating only happens in CI, and currently we don't have the capability to run it but ignore results, but support is there in the version generator

2021-04-02 13:41 UTC, jon-betts commented on bin/install-python.sh
>      pyenv install --skip-existing "$python_version"
We need to include a version of this file in `hdev` ideally so as not to have to copy paste this change into every repo, although I'm not sure how yet.

2021-04-02 16:48 UTC, seanh commented on .github/workflows/pythonpackage.yml
> +        python-version: 3.9.2
So I guess this Python version is used to _run_ `bin/python_codes.py`?

2021-04-02 16:48 UTC, seanh commented on .github/workflows/pythonpackage.yml
> +        echo "::set-output name=headline_version::${HEADLINE_VERSION}"
Whereas the `headline_version` from `bin/python_codes.py --style headline` is used to actually run the `lint`, `package` and `publish` jobs. And the `python_versions` from `bin/python_codes.py --style gha` are used to run the `test` job

2021-04-02 17:07 UTC, seanh requested changes
I'm not sure about the future versions stuff. I think we might want `make sure` and `make testall` to do the same thing as is done on CI. Otherwise they could be failing locally but passing on CI which might just be confusing.

I think we might just want to add a new Python version to `.python-versions`, fix any bugs, and have it be run both locally and on CI. I'm not sure we'll want `make` commands to be running some Python versions locally that don't get run on CI.

Note that you can always do `tox -e py39-tests` manually to run the tests with some future version of Python

2021-04-02 17:07 UTC, seanh commented on .github/workflows/pythonpackage.yml
> +      headline_version: ${{ steps.list-python-versions.outputs.headline_version }}
Might call this `headline_python_version` just to be clear

2021-04-02 17:07 UTC, seanh commented on Makefile
> +	@tox -qe \{`./bin/python_codes.py`\}-tests
We should add `make sure` to the packages as well and have it run `checkformatting lint testall`

2021-04-02 17:07 UTC, seanh commented on .python-version
> +3.6.13
I wonder whether `# floating` is just the default behaviour that we want all the time

2021-04-05 13:30 UTC, jon-betts commented on .python-version
> +3.6.13
Depends how you feel about whether what you run locally should reflect what happens in CI. The general thrust of the requirements files has been to ensure we run the same thing in both.

Let me know which way to go.

2021-04-05 13:30 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +        python-version: 3.9.2
Yes, we need something to bootstrap it

2021-04-05 13:38 UTC, jon-betts commented on .python-version
> +3.6.13
On the other hand I'd suggest that if we want it on every one, put it on every one. This model supports any way of working, we don't need to limit it to one.

2021-04-05 13:38 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +        echo "::set-output name=headline_version::${HEADLINE_VERSION}"
I've removed the variables.

2021-04-05 13:38 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +        HEADLINE_VERSION=`./bin/python_codes.py --style headline`
I've done this. It's a bit odd as it usually returns multiple versions.

2021-04-05 13:38 UTC, jon-betts commented on .github/workflows/pythonpackage.yml
> +      headline_version: ${{ steps.list-python-versions.outputs.headline_version }}
Done.

2021-04-05 13:43 UTC, jon-betts commented
As discussed in https://github.com/hypothesis/product-backlog/issues/1199:

> * Optionally target an "aspirational" version of Python we cannot reach yet to:
>   * Give us warning of any additions which break compatibility with that version
>   * ... or give us notice when we become compatible with that version
> * Testing against all versions should be:
>   ...
>   * Required to pass in all but the "aspirational" target if the "asprirational" target version has never passed
>   * Required to pass in all cases if the "aspirational" target has ever passed

The future requirement is a basic way of achieving this. We add future, and then we can be notified locally but CI will continue to pass. If we notice that local tests are passing for the version we can remove the "future" tag and it will be tested in CI achieving the last part.

While we can test adhoc versions by editing the version file temporarily and running a custom tox command but it:

 * Doesn't allow us to record a decision to formally attempt to move to supporting a version (you have to remember it yourself)
 * Is unlikely to ever become part of common practice
 
An improvement to this process would be to have the tests run on CI, but only "warn" on failure, if such a thing is possible.

2021-04-05 13:55 UTC, jon-betts commented on Makefile
> +	@tox -qe \{`./bin/python_codes.py`\}-tests
I've added a `make sure` command locally. We can move it to the cookie cutter when other behaviors move out.

2021-04-05 13:58 UTC, jon-betts commented
The `# floating` behavior was added to support the commit that @marcospri made for the `hdev` project. I think the way I'd suggest approaching this is:

* If the system can achieve the behavior we want, it's good
* If it also supports other behaviors too that's better
* Because it allows us to change our mind and experiment without changing the system, only the config

So many of the suggestions in the PR above actually are already in place / could be easily. e.g.:

 * "Run the same versions locally and in CI" - `h_matchers` has no `'# future` tagged versions, so this is in place
 * "Have all the items be floating"  - Add `# floating` to all versions

2021-04-05 15:51 UTC, seanh approved these changes

2021-04-06 13:08 UTC, merged